### ISSUE TITLE
Stacking jobs on m1 mac can not start due to "wrong" memory report

### ISSUE THREAD

**Issue by IIlllII** [Rolf-Hempel/PlanetarySystemStacker#50] opened 2022-06-15 20:14 UTC
Awesome software, thanks so much for making it!

On my m1 mac under rosetta2 https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory "available" reports around 1.5 GB free memory which is nonsense. This prevented me from starting a stacking job with 23 6240 × 4160 images, it stopped with

> "Error: Too little * RAM for this job, continuing with the next one"

Once I changed the code to use "total" reported by psutil this job worked fine.

I think this is related to all the listed memory "types" here not being reported as "available".

<img width="593" alt="Screenshot 2022-06-15 at 21 41 05" src="https://user-images.githubusercontent.com/8010979/173911423-9e05bc6f-833b-4699-b234-66f1a7951f3d.png">

Not under rosetta2 psutil "available" reports a more correct, but also way too low 5GB.

A manual override in configuration would be very nice I think. So that it would be possible to work around this bad reporting. If a PR with this would be welcomed I might take a stab at it.

**Comment by Rolf-Hempel** [comment] 2022-06-19 07:23
The problem is to get this right in a portable manner. I just relied on the statement in the documentation: "Note: if you just want to know how much physical memory is left in a cross platform fashion simply rely on the available field." which worked fine on my Windows and Linux machines. Now you write that on your M1 mac that is not the case.

I wonder what the figures in the image you presented mean. If you add "Memory Used" and "Cached Files", this could represent the current memory usage. If you compare that with the total memory ("Physical Memory" plus "Swap Used"), some 2 GB remain as "available". So, the reported 1.5 GB look plausible to me. This is interpretation seems to be wrong. Do you know why?

A manual override in configuration sounds dangerous to me. If users make the wrong decision here, the program could crash. A better alternative seems to me to make the psutil call platform dependent. What strings do the calls to "platform.system()" and "platform.processor()" report on your machine? And is "total" really a safe option in the psutil call on your machine? If the psutil documentation is correct, this always reports the total memory, regardless what other programs are running. Does this mean that PSS goes into swapping? That would not be a good idea, would it?

Since I'm not a Mac user, I cannot test this myself. Therefore, I very much rely on your help to get it right. Sorry!

**Comment by IIlllII** [comment] 2022-06-20 20:42
It seems to me that macOs will give out memory and take the performance hit from compression/swapping if it occurs. It takes a lot for it to kill any process to free up memory in my experience (I do not think I have ever experienced it).

I did some experiments now, using my modified version where I use the reported "total" as memory limit: 

- One where I started 3 stacking jobs (processing was sequential but data was held in memory all the time) with the same data, each reporting to take 10GB. It worked fine. Responsive and fast UI while running.

- A second experiment where I started an APP job and 2 different PlanetarySystemStacker jobs. These all had different data and all ran simultaneously. progress was not great, but fine. System was responsive all the time.

So my 16GB m1 deals fine with 30GB by using swap and compression. It also seems to me that the memory access pattern is quite swap friendly. How older systems and older hardware will respond is hard to say though.

Here is the the memory situation while these ran, and this describes the reported data.
https://support.apple.com/guide/activity-monitor/view-memory-usage-actmntr1004/mac

<img width="1114" alt="Screenshot 2022-06-19 at 14 42 45" src="https://user-images.githubusercontent.com/8010979/174668188-fe4f6ece-30a5-497e-a9d3-b9241a5f58de.png">
<img width="1327" alt="Screenshot 2022-06-19 at 15 42 10" src="https://user-images.githubusercontent.com/8010979/174668195-5c253670-b497-490e-a33b-9c9046062e36.png">

https://developer.apple.com/forums/thread/105088?login=true
This thread suggests decoupling user data size and memory use as well as responding to memory pressure events (not sure what that would mean in python, maybe numpy allocation errors). That seems like a large and possibly quite complex change.

It seems really hard to reason about the memory situation up front in macOs now with compression. I do not think my use of "total" is ideal, that was mostly a workaround to get my jobs to start due to this wrong psutil reporting under rosetta2. When it is correctly reported "available" seems like a fine default (on the low end, but fine as long as the job can be started).

I still think a configuration based explicit override/limit would be a good idea. I do see your point that this might cause crashes for users if used wrong though. Maybe it could come with a warning in the configuration? If I explicitly ticked a box with such a warning and gave the application a lot of memory, I would accept a process crash or degraded OS user experience as my own fault.

Lastly:
```
print(platform.system())
print(platform.processor())
```
gives:
```
Darwin
i386
```
On my system.

**Comment by Rolf-Hempel** [comment] 2022-06-22 11:36
Thank you very much for the interesting details! It really looks like MacOS is a world of its own.

I'm thinking about an elegant way to add a configuration option to set the maximum memory usage explicitly. At the moment the user can specify the "buffering level" or leave it as "automatic". What about this alternative:

- A checkbox "Set maximum memory usage explicitly" is added, with a text field next to it where the user can enter the memory size in Gigabytes. If the checkbox is unchecked, the text field is grayed out (deactivated). The user can still use the "data buffering level" drop down menu to control the memory usage (as before).
- If the checkbox is checked and a valid memory size (>0, numeric value) is entered, the "data buffering level" menu is set to the fixed value "auto" and deactivated. After all, if the user gives PSS a fixed amount of memory, PSS should feel free to use as much of it as possible (by setting the buffering level dynamically).
- If the checkbox is checked, a warning text could appear saying that PSS has no responsibility for enough memory being available.

What do you think? The largest part of the implementation would be on the GUI side (and updating the documentation). To change the workflow would be relatively easy.

**Comment by Rolf-Hempel** [comment] 2022-06-24 07:30
Sounds good to me! Please take the "prototype" branch as a starting point for your implementation work. On that branch I have made some changes already which will go into the next release (0.9.2). Once everything is stable on "prototype", I will merge the changes into "master" and prepare the release.

**Comment by Rolf-Hempel** [comment] 2022-06-24 13:58
I just changed the GUI on the prototype branch to include the new features in the workflow configration tab. The added logic is not implemented yet. Please start from this software version if you want to implement the new behaviour.

**Comment by Rolf-Hempel** [comment] 2022-06-27 14:14
Hi, 

Thank you very much for sending the pull request. I'm impressed how quickly you found your way through the PSS source code and made the changes in the right places. Well done!

I merged your code with the "prototype" branch and did a few tests. So far the changes you made look good to me. I will do more detailed tests to make sure that there are no unwanted side effects.

Thanks again, and all the best,
 Rolf

**Comment by IIlllII** [comment] 2022-06-27 22:28
Thanks, and thanks for accepting the change :).
The code is well organized so it was easy to read and work on.

I must say am really looking forward to use PSS more once the weather gets better for observations here in Norway and I can capture more data.

All the best,
Jonas

**Comment by Rolf-Hempel** [comment] 2022-06-30 15:04
Hi Jonas,

I added the option to set the RAM size limit explicitly in command line mode as well.

Please have a look at the current code on the "prototype" branch. I changed the warning which appears if the user sets the RAM explicitly. I removed the pop up window. Instead, as soon as the option is activated, the warning is displayed in red ink in the prameter window. I find that more lightweight, and the effect should be the same.

 All my tests so far worked well. The only thing missing is the update of the documentation. I will work on that next week.

**Comment by Rolf-Hempel** [comment] 2022-07-09 07:28
Hi Jonas,

I updated the documentation (in English and German) on the „prototype“ branch. I think that the feature is implemented completely by now, so I can close the issue.

Btw.: Are you interested in joining the development team? You know the code structure well enough, and you have already contributed some code. What do you think?

All the best,
 Rolf

**Closed by Rolf-Hempel** 2022-07-09 07:28 UTC

**Comment by IIlllII** [comment] 2022-08-12 06:49
Hi, sorry for the late reply (vacation time here).

Thanks for the offer, that would be nice. It should be mentioned that I have a very varying amount of time to dedicate to development outside of my dayjob, but if that is ok, then I am interested.

Jonas
